[package]
name = "tono-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tono-core = { path = "../../../crates/tono-core" }
tono-service-protocol = { path = "../../../service", version = "2.6.7" }
tono-service-client = { path = "../tono-service-client" }
tono-logging = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
