// Objective-C API for talking to github.com/sagernet/sing-box/experimental/tonomobile Go package.
//   gobind -lang=objc github.com/sagernet/sing-box/experimental/tonomobile
//
// File is generated by gobind. Do not edit.

#ifndef __Tonomobile_H__
#define __Tonomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TonomobileAdmission;
@class TonomobileSession;

@interface TonomobileAdmission : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)locations;
- (TonomobileSession* _Nullable)start:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)watermark;
@end

@interface TonomobileSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)close;
- (BOOL)probe:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)packet error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull TonomobileIdentity(void);

/**
 * Discovery admits all bytes without choosing a route or creating a session.
 */
FOUNDATION_EXPORT NSString* _Nonnull TonomobileLocations(NSData* _Nullable catalog, NSData* _Nullable policy, NSString* _Nullable previous, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TonomobileAdmission* _Nullable TonomobilePrepare(NSData* _Nullable catalog, NSData* _Nullable policy, NSString* _Nullable selected, NSString* _Nullable previous, NSError* _Nullable* _Nullable error);

#endif
