import Foundation

actor InitialDataLoader {
    func load() -> InitialDiskSnapshot {
        let storage = ConfigStorage.shared
        let rawSubscriptionYAML = storage.loadRawSubscriptionYAML()
        var rules = storage.loadRules() ?? []

        // Legacy subscription repair is useful only in the isolated developer
        // profile. Do the potentially large YAML parse here instead of during
        // the first SwiftUI render.
        if AppProfile.isDev {
            let needsRepair = rules.isEmpty
                || rules.contains { $0.policyName == nil && $0.policy == .proxy }
            let yamlHasRules = rawSubscriptionYAML?.components(
                separatedBy: .newlines
            ).contains {
                $0.trimmingCharacters(in: .whitespaces) == "rules:"
            } ?? false
            if needsRepair, yamlHasRules, let rawSubscriptionYAML {
                let parsed = ConfigParser.parseClashYAMLRules(
                    rawSubscriptionYAML,
                    source: .subscription
                )
                if !parsed.isEmpty {
                    rules = rules.filter { $0.source == .user } + parsed
                    storage.saveRules(rules)
                }
            }
        } else {
            // Production runtime rules are generated by ConfigPipeline and
            // queried from Mihomo. Never surface stale editable legacy rules.
            rules = []
        }

        return InitialDiskSnapshot(
            proxyRegions: storage.loadProxyRegions() ?? [],
            rules: rules,
            cachedCatalog: storage.loadManagedExitCatalog(),
            cachedTrafficPolicy: storage.loadManagedTrafficPolicy(),
            config: storage.loadConfig()
        )
    }
}
