export const batchCopy = {
  title: '本次批量操作',
  lifetime: '结果仅保留在当前标签页，刷新页面后清除。离开客户列表不会取消已确认的请求。',
  safety: '只重试明确失败的项；已提交和结果未知的写入不会重发。入队不代表客户端已生效。',
  previous: '先核对并收起上一次结果，再发起新批次',
  retry: '只重试明确失败项',
  retryBody: (n: number) => `只处理上次明确失败的 ${n} 项，不重复提交成功或结果未知的写入。续期沿用第一次确认的目标日期，不再加 30 天。`,
  inspect: '核对最新结果',
  dismiss: '收起本次结果',
  openCustomer: '查看客户',
  discover: '读取可接收动作的设备',
  renew: '续期',
  refresh: '刷新目录',
  receipt: '回执编号',
  states: {
    waiting: '等待处理', checking: '核对中', submitting: '提交中',
    submitted: '已入队，待客户端领取', delivered: '已下发，待完成回执',
    done: '结果已核对', failed: '明确失败', unknown: '结果未知', skipped: '未执行',
  },
  summary: (done: number, submitted: number, failed: number, unknown: number) =>
    `已核对 ${done} · 待回执 ${submitted} · 明确失败 ${failed} · 结果未知 ${unknown}`,
  readFailed: '读取失败，可重试读取；没有发送写请求。',
  refused: (status: number) => `请求被拒绝（HTTP ${status}），未接受本次写入。`,
  uncertain: '未拿到可靠的写入回执。先核对结果，不要重复提交。',
  changed: '到期日已变化，本次没有写入。请打开客户核对后重新选择。',
  renewalVerified: '重新读取的到期日与本次目标日期一致。',
  renewalUnverified: '尚未读到本次目标日期；没有再次写入，请核对客户。',
  receiptMissing: '尚未查到这个回执，不能据此判定失败或重新提交。',
  receiptFailed: '读取回执失败，保留最后已知状态；没有重新下发。',
  deviceDone: '客户端报告完成；不等同于客户连接体验已恢复。',
  deviceFailed: '客户端报告失败或回执已过期。请查看客户后决定是否另发动作。',
  targetExpiry: '本次目标到期',
} as const;
