export const copy = {
  brand: 'Tono',
  brandSub: '运维',
  pages: {
    today: '今天',
    nodes: '节点',
    customers: '客户',
    clients: '客户端',
    settings: '设置',
  } as const,
  emptyMigrated: '尚未迁移，请用 /ops/',
  searchPrompt: '搜索节点或页面',
  commandEmpty: '没有匹配项',
  commandPages: '页面',
  commandNodes: '节点',
  theme: {
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
  } as const,
  privacy: '隐私',
  sourceOk: '数据源 正常',
  sourceUnknown: '数据源 未知',
  sessionExpired: '登录已过期',
  sessionExpiredBody: '登录已过期，页面上的数据不会再更新。重新登录后继续。',
  reload: '重新登录',
  viewCards: '卡片',
  viewTable: '表格',
  listed: '在售',
  unlisted: '未上架',
  occupancy: '在用人数',
  occupancyUnit: '人',
  periodTraffic: '本周期流量',
  customerPath: '客户去程',
  notWired: '未接入',
  mainlandReturn: '大陆回程',
  renew: '续费/到期',
  lastMeasured: '最后测量',
  missing: '—',
  noQuota: '未设额度',
  exhaustEta: '预计耗尽',
  remaining: '剩余',
  status: '状态',
  node: '节点',
  inUse: '在用',
  loading: '载入中',
  loadError: '载入失败',
  emptyList: '没有节点',
  tableError: '表格没载入上来',
  retry: '重试',
  close: '关闭',
  facts: {
    ip: '地址',
    os: '系统',
    provider: '供应商',
    tags: '线路',
    ports: '端口',
  } as const,
  sources: {
    agent: '探针',
    quality: '质量',
    catalog: '目录',
    profile: '画像',
    live: '三网',
    none: '未接入',
  } as const,
  health: {
    lost: '失联',
    blocked: '被墙',
    degraded: '劣化',
    ok: '正常',
    unmeasured: '未测',
  } as const,
  count: {
    listed: (n: number) => `${n} 台在售`,
    blocked: (n: number) => `${n} 台被墙`,
    unmeasured: (n: number) => `${n} 台未测`,
  },
  unit: {
    person: '人',
    ms: 'ms',
    pct: '%',
  },
} as const;

export type PageId = keyof typeof copy.pages;
