export const copy = {
  brand: 'Tono',
  brandSub: '运维',
  pages: {
    today: '今天',
    nodes: '节点',
    customers: '客户',
    clients: '客户端',
    settings: '设置',
  } as const,
  emptyMigrated: '尚未迁移，请用 /ops/',
  searchPrompt: '搜索节点或页面',
  commandEmpty: '没有匹配项',
  commandPages: '页面',
  commandNodes: '节点',
  theme: {
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
  } as const,
  privacy: '隐私',
  sourceOk: '数据源 正常',
  sourceUnknown: '数据源 未知',
  sessionExpired: '登录已过期',
  sessionExpiredBody: '登录已过期，页面上的数据不会再更新。重新登录后继续。',
  reload: '重新登录',
  viewCards: '卡片',
  viewTable: '表格',
  listed: '在售',
  unlisted: '未上架',
  occupancy: '在用人数',
  occupancyUnit: '人',
  periodTraffic: '本周期流量',
  customerPath: '客户去程',
  notWired: '未接入',
  mainlandReturn: '大陆回程',
  renew: '续费/到期',
  lastMeasured: '最后测量',
  missing: '—',
  noQuota: '未设额度',
  exhaustEta: '预计耗尽',
  remaining: '剩余',
  status: '状态',
  node: '节点',
  inUse: '在用',
  loading: '载入中',
  loadError: '载入失败',
  emptyList: '没有节点',
  tableError: '表格没载入上来',
  retry: '重试',
  close: '关闭',
  facts: {
    ip: '地址',
    os: '系统',
    provider: '供应商',
    tags: '线路',
    ports: '端口',
  } as const,
  sources: {
    agent: '探针',
    quality: '质量',
    catalog: '目录',
    profile: '画像',
    live: '三网',
    none: '未接入',
  } as const,
  /** Who measured it, in one word — the second half of every `—`. */
  sourceWord: {
    collector: '采集',
    komari: '探针',
    telemetry: '上报',
    catalog: '目录',
    profile: '画像',
    engine: '判定',
    jobs: '任务',
    manual: '手填',
  } as const,
  health: {
    lost: '失联',
    blocked: '被墙',
    degraded: '劣化',
    ok: '正常',
    unmeasured: '未测',
  } as const,
  count: {
    listed: (n: number) => `${n} 台在售`,
    blocked: (n: number) => `${n} 台被墙`,
    unmeasured: (n: number) => `${n} 台未测`,
  },
  /** A span, not a point: "已持续 2 小时" reads wrong as "2 小时前". */
  lasting: {
    now: '不到 1 分钟',
    minutes: (n: number) => `${n} 分钟`,
    hours: (n: number) => `${n} 小时`,
    days: (n: number) => `${n} 天`,
  },
  ago: {
    now: '刚刚',
    minutes: (n: number) => `${n} 分钟前`,
    hours: (n: number) => `${n} 小时前`,
    days: (n: number) => `${n} 天前`,
  },
  unit: {
    person: '人',
    ms: 'ms',
    pct: '%',
  },

  /* ---------------------------------------------------------------- 客户 */

  customerHealth: {
    unreachable: '连不上',
    unstable: '不稳',
    unreported: '未上报',
    offline: '离线',
    ok: '正常',
  } as const,
  lifecycle: {
    active: '在用',
    suspended: '已停用',
    expired: '已到期',
  } as const,
  customerCount: {
    all: (n: number) => `${n} 位客户`,
    online: (n: number) => `${n} 位在线`,
    unreachable: (n: number) => `${n} 位连不上`,
  },
  platform: {
    macos: 'macOS',
    windows: 'Windows',
    linux: 'Linux',
    android: 'Android',
    ios: 'iOS',
  } as const,
  unreleased: '未发布',
  customerColumns: {
    status: '状态',
    customer: '客户',
    devices: '设备',
    node: '当前节点',
    failure: '最近失败',
    usage: '本期流量',
    services: '服务使用',
    minVersion: '最低版本',
    expires: '到期',
  } as const,
  deviceUnit: '台',
  overQuota: '超额',
  usageTitle: (used: string, quota: string, remain: string) => `已用 ${used} / 额度 ${quota} · 剩余 ${remain}`,
  usageNoQuota: (used: string) => `已用 ${used} · 未设额度`,
  emptyCustomers: '没有客户',

  customerActions: {
    diagnose: '发起远程诊断',
    resend: '重发凭证',
    changeExpiry: '改到期',
    suspend: '停用',
    blocked: '接口未接入',
  } as const,
  customerSections: {
    now: '现在',
    timeline: '连接时间线',
    activity: '使用时段',
    destinations: '流量去向',
    services: '服务使用',
    carriers: '按运营商的路径',
    devices: '设备',
    diagnostics: '诊断报告',
    chores: '待办',
    billing: '账务与用量',
  } as const,
  now: {
    connected: '在连',
    node: '节点',
    since: '连了多久',
    device: '设备',
    version: '版本与系统',
    carrier: '运营商与省份',
    yes: '在连',
    no: '没连',
  } as const,
  quota: '额度',
  expiresAt: '到期',

  timelineFilters: {
    all: '全部',
    failed: '只看失败',
    device: '设备',
    week: '最近 7 天',
  } as const,
  timelineColumns: {
    at: '时间',
    outcome: '结果',
    node: '节点',
    stage: '阶段',
    code: '代码',
    elapsed: '耗时',
    client: '平台与版本',
    carrier: '运营商',
  } as const,
  daySummary: (ok: number, fail: number, switched: number) => `${ok} 次连上 · ${fail} 次失败 · ${switched} 次换节点`,
  /** The upload went through the tunnel, so the carrier on it is the exit's. */
  carrierViaExit: '这条上报走的是隧道，看到的是出口的运营商',
  emptyTimeline: '这位客户还没有上报过连接',
  noCarrierPaths: '还没有够判断的连接记录',
  eventWord: {
    connectBegin: '开始连接',
    connectOk: '连上',
    connectFail: '没连上',
    nodeSwitch: '换节点',
    connectCatalogFailover: '换线路',
    healthProbeFail: '探测没过',
    protectedOffline: '掉线保护',
    coreRestart: '内核重启',
    reconnectScheduled: '准备重连',
    networkChange: '网络变了',
    disconnectOk: '断开',
    releaseFail: '发布失败',
    syncFail: '同步失败',
  } as const,
  stageWord: {
    dial: '拨号',
    handshake: '握手',
    tls: '加密',
    catalog: '取节点',
    probe: '探测',
  } as const,
  codeWord: {
    ECONNREFUSED: '对方端口没人应答',
    ETIMEDOUT: '连接超时，没等到回应',
    EHOSTUNREACH: '到不了这台机器',
    TLS_HANDSHAKE_TIMEOUT: '加密握手超时',
    REALITY_AUTH_FAIL: '身份校验没通过',
    CATALOG_STALE: '客户端手里的节点单子太旧',
    DNS_FAIL: '域名解析失败',
    UNKNOWN: '客户端没说原因',
  } as const,

  activityLegend: '每格一小时，深色是已连接',
  activityHour: (hour: string, minutes: number) => `${hour} 已连接 ${minutes} 分钟`,
  weekday: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'] as const,

  destinationColumns: {
    site: '目的地',
    route: '路由',
    node: '节点',
    connections: '连接数',
    bytes: '流量',
    action: '',
  } as const,
  route: {
    cloud: '云出口',
    residential: '家宽',
    direct: '直连',
    reject: '拒绝',
    unknown: '未知',
  } as const,
  markDirect: '标为直连候选',
  markDirectBlocked: '接口未接入',

  serviceColumns: {
    family: '服务',
    route: '走哪条路',
    bytes: '7 天流量',
    lastSeen: '最近使用',
  } as const,
  serviceName: {
    claude: 'Claude',
    chatgpt: 'ChatGPT',
    grok: 'Grok',
    gemini: 'Gemini',
    meta: 'Meta',
    other: '其他',
  } as const,

  carrierMatrix: {
    carrier: '运营商',
    okRate: '成功率',
    latency: '中位耗时',
    samples: '次数',
  } as const,
  deviceColumns: {
    name: '设备',
    platform: '平台',
    version: '版本',
    os: '系统',
    lastSeen: '最近在线',
    node: '当前节点',
    action: '动作',
  } as const,
  deviceActionBlocked: (platform: string) => `${platform} 客户端还没有这个动作`,
  foldOpen: '展开',
  foldShut: '收起',
  noDiagnostics: '还没有回传的诊断报告',
  noChores: '没有待办',
  billingFacts: {
    plan: '套餐',
    deviceLimit: '设备上限',
    usage: '本期用量',
    quota: '额度',
    expires: '到期',
    since: '首次开通',
  } as const,

  /* ---------------------------------------------------------------- 今天 */

  todayVerdict: (incidents: number, customers: number) => `现在 ${incidents} 个事故，影响 ${customers} 位客户`,
  todayClear: (when: string) => `现在没有事故。上次事故 ${when} 已恢复。`,
  todayNeverAny: '现在没有事故。',
  todayTabs: {
    open: '进行中',
    resolved: '最近恢复',
    chores: '待办',
  } as const,
  tabCount: (n: number) => `${n}`,
  severity: {
    severe: '严重',
    warn: '注意',
    notice: '提示',
  } as const,
  incidentImpact: (n: number) => `影响 ${n} 位客户`,
  incidentImpactNode: (n: number) => `影响 ${n} 台节点`,
  incidentOpenFor: '已持续',
  incidentLastSeen: '最后测量',
  incidentResolvedAt: '已恢复',
  incidentPrimary: {
    ack: '认领',
    snooze: '静默 4 小时',
    resolve: '标记已处理',
    note: '备注',
  } as const,
  incidentDrawer: {
    timeline: '时间线',
    affected: '受影响客户',
    evidence: '证据',
    actions: '动作',
    deliveries: '推送记录',
    notePrompt: '写一句备注',
    noteSend: '记下',
  } as const,
  incidentEvent: {
    opened: '开始',
    escalated: '升级',
    deescalated: '降级',
    acked: '已认领',
    snoozed: '已静默',
    note: '备注',
    job: '执行',
    alert: '推送',
    resolved: '已恢复',
  } as const,
  deliveryStatus: {
    pending: '待发',
    sent: '已发',
    failed: '没发出去',
    suppressed: '没重复推送',
  } as const,
  jobStatus: {
    queued: '排队中',
    leased: '执行中',
    succeeded: '成功',
    failed: '失败',
    cancelled: '已取消',
    expired: '已过期',
  } as const,
  emptyIncidents: '没有进行中的事故',
  emptyResolved: '最近 7 天没有恢复记录',
  actionFailed: '动作没做成',
  choreKindOther: '待办',
  choreKind: {
    renew: '续费',
    quota: '额度',
    expiry: '到期',
    version: '版本过旧',
    profile: '缺资料',
  } as const,
  chore: {
    nodeRenew: (node: string, when: string) => `${node} ${when} 续费`,
    nodeQuota: (node: string, pct: string) => `${node} 本期流量已用 ${pct}`,
    nodeProfile: (node: string) => `${node} 还没登记价格与续费日`,
    customerExpiry: (who: string, when: string) => `${who} ${when} 到期`,
    customerQuota: (who: string, pct: string) => `${who} 本期流量已用 ${pct}`,
    customerVersion: (who: string, version: string) => `${who} 还在跑 ${version}`,
    customerProfile: (who: string) => `${who} 没上报过平台与版本`,
  },
  commandCustomers: '客户',
  commandIncidents: '事故',
} as const;

export type PageId = keyof typeof copy.pages;
