/** 客户: the list's dashboard band and charts, and the timeline's daily shape. */
export const customerBoardCopy = {
  customerBoard: {
    stat: {
      online: '现在在线',
      seenWeek: '7 天内来过',
      failedDay: '24 小时有失败',
      usage: '本期流量',
      nearQuota: '额度快用完',
      expiring: '7 天内到期',
    },
    onlineSub: (reporting: number) => `${reporting} 位上报了状态`,
    onlineNone: '还没有人上报',
    seenWeekSub: (active: number) => `在用 ${active} 位`,
    failedDaySub: '最近一次失败在 24 小时内',
    usageSub: (unmetered: number) => (unmetered === 0 ? '每位都有计量' : `${unmetered} 位没计量`),
    nearQuotaSub: '用了八成以上额度',
    expiringSub: (expired: number) => (expired === 0 ? '没有过期还在用的' : `另有 ${expired} 位已过期`),
    expiry: '到期分布',
    expiryLead: '在用客户按到期的那一周；已过期的在最左',
    expiryLabel: '在用客户按到期周数的人数',
    expiryEmpty: '8 周内没有人到期',
    expiryStack: '人数',
    lapsed: '已过期',
    weekOf: (week: number) => (week === 0 ? '本周' : `+${week} 周`),
    top: '流量最多',
    topLead: '本期流量，对着额度',
    topEmpty: '还没有人报过流量',
    source: '客户列表',
    quotaOf: (used: string, quota: string) => `${used} / ${quota}`,
    action: '操作',
    more: (total: number) => `显示全部 ${total} 个`,
    fewer: (first: number) => `只看前 ${first} 个`,
    days: '每天的连接',
    daysLead: '按天，成功与失败叠加',
    daysLabel: '每天成功与失败的连接次数',
    daysOk: '成功',
    daysFail: '失败',
  },
} as const;
