// 客户 的写动作：开通、到期、停用、家宽、Claude 号、设备动作。
//
// 每一句"会发生什么"都写成结果，不写成问句：操作员按下去之前要读的是客户
// 那一头会变成什么样，不是"确定吗"。
export const customerActionCopy = {
  /* ------------------------------------------------------------ 开通 */

  onboard: '开通',
  onboardTitle: '开通客户',
  onboardLead: '先让客户能用这个邮箱登录，登录过之后才能绑家宽和 Claude 号。',
  onboardFields: {
    email: '客户邮箱',
    plan: '套餐',
    expiresAt: '到期',
    line: '贴一行家宽',
    homeExit: '或从库存里选',
    accountRef: 'Claude 账号',
    pooled: '或从号池里选',
    notes: '备注',
    contact: '联系方式',
  } as const,
  onboardHints: {
    email: '客户用来收验证码的邮箱',
    line: '一行 host:port:user:pass；填了就不用从库存选',
    expiresAt: '留空就是不限到期',
    accountRef: '填了就不用从号池选',
  } as const,
  onboardSave: '开通',
  onboardAgain: '客户登录过了，再开通一次',
  onboardPick: {
    none: '先不选',
    homesEmpty: '库存里没有闲置线路',
    poolEmpty: '号池是空的',
    notReady: '还没载入',
  } as const,
  onboardSteps: {
    allowlisted: '可以用这个邮箱登录',
    registered: '已经在客户端登录过',
    identity: '连接凭证已经生成',
    home: '已绑家宽',
    claude: '已开通 Claude 号',
  } as const,
  onboardStepWaiting: {
    registered: '还没登录，请客户先用这个邮箱在客户端收验证码',
    identity: '连接凭证要等客户登录后才生成',
    home: '还没绑家宽',
    claude: '还没开通 Claude 号',
  } as const,
  onboardConfirmBody: (email: string) => `${email} 会进允许登录的名单，客户端登录之后就能连。填了的家宽和 Claude 号一起记在这位客户名下。`,
  onboardDone: (email: string) => `${email} 已经可以用了`,
  onboardExtrasIgnored: '这次填的家宽和 Claude 号没有保存，等客户登录后再开通一次。',
  onboardPlanNone: '不填',

  /* -------------------------------------------------------- 批量动作 */

  selectRow: '选中这一行',
  selectedCount: (n: number) => `选中 ${n} 位客户`,
  clearSelection: '取消选择',
  batchRefresh: '给落后客户刷目录',
  batchRefreshTitle: '刷新目录',
  batchRefreshBody: (people: number) => `会给选中的 ${people} 位客户名下每一台 macOS / Windows 设备各下发一次刷新目录，客户端下次上报时执行。不改到期，也不动流量。`,
  batchRefreshNoDevices: '选中的客户名下没有能收动作的设备',
  batchRenew: '到期客户续 30 天',
  batchRenewTitle: '续 30 天',
  batchRenewBody: (n: number) => `选中的 ${n} 位客户，各自从今天和原到期日里靠后的那天起再加 30 天。不限到期的不会被改。`,
  batchRenewNobody: '选中的客户都不限到期，续期改不动任何一位',
  batchDone: (n: number) => `已处理 ${n} 位客户`,
  batchPartly: (done: number, failed: number) => `${done} 位做成了，${failed} 位没做成`,

  /* ------------------------------------------------------ 客户 360 头 */

  customerHeadActions: {
    diagnose: '发起远程诊断',
    resend: '重发凭证',
    changeExpiry: '改到期',
    suspend: '停用',
    restore: '恢复',
  } as const,
  noDevices: '这位客户名下还没有设备',
  pickDevice: '选一台设备',
  diagnoseTitle: '发起远程诊断',
  diagnoseBody: (device: string) => `会给 ${device} 下发一次诊断快照，客户端下次上报时执行，最多等 5 分钟。不会断开正在用的连接。`,
  resendTitle: '重发凭证',
  resendBody: (devices: number) => `会给 ${devices} 台设备各下发一次刷新目录，客户端拿到新目录时凭证一起更新。不会断开正在用的连接。`,
  expiryTitle: '改到期',
  expiryLead: '到期只挡登录和取目录，不删数据，也不撤设备。',
  expiryField: '到期日',
  expiryRenew: '续 30 天',
  expiryClear: '取消到期',
  expirySet: '设到期',
  expiryRenewBody: (email: string, date: string) => `${email} 的到期改成 ${date}。从今天和原到期日里靠后的那天算起。`,
  expirySetBody: (email: string, date: string) => `${email} 的到期改成 ${date}。到了这一天客户端就取不到目录。`,
  expiryClearBody: (email: string) => `${email} 从此不限到期，待办里也不会再提醒续费。`,
  expiryInvalid: '这个日期看不懂，没有保存。',
  expiryAlreadyClear: '这位客户本来就不限到期',
  suspendTitle: '停用账号',
  suspendBody: (email: string) => `${email} 马上不能登录，名下设备会被撤销，家宽退回库存，在用的 Claude 号退出。确认后才会执行。`,
  suspendReason: '停用原因',
  suspendConfirm: '停用',
  restoreTitle: '恢复账号',
  restoreBody: (email: string) => `${email} 可以重新登录。设备要自己再登一次，家宽和 Claude 号不会自动绑回来。`,
  restoreConfirm: '恢复',

  /* ------------------------------------------------------ 账务与用量 */

  billingEdit: '改账务',
  billingFieldPlan: '套餐',
  billingFieldExpires: '到期',
  billingFieldContact: '联系方式',
  billingFieldNotes: '备注',
  billingContactHint: '微信或者别的联系方式',
  billingWriteOnly: '联系方式和备注读不回来：留空就是不改，填了就整条换掉。',
  billingPlanHint: '只有 Claude 这一种套餐，或者不填',
  resetUsage: '清零本期用量',
  resetUsageTitle: '清零本期用量',
  resetUsageBody: (used: string) => `现在的 ${used} 算已经结过，从这一刻重新算。服务器上的历史累计不会删，这一步也撤不回。`,
  resetUsageConfirm: '清零',
  resetUsageNothing: '本期还没有用量，不用清零。',

  /* ---------------------------------------------------------- 家宽 */

  homeSection: '家宽',
  homeNone: '还没绑家宽，走的是节点的公共出口',
  homeFacts: {
    line: '线路',
    address: '地址',
    kind: '类型',
    status: '状态',
    defaultNode: '默认节点',
    boundAt: '绑定时间',
  } as const,
  homeStatus: {
    active: '在用',
    disabled: '停用',
    retired: '已退役',
  } as const,
  homeKind: {
    socks5: '家庭宽带',
    catalog: '目录节点',
  } as const,
  homeBind: '绑定',
  homeRebind: '换线',
  homeUnbind: '解绑',
  homePickLine: '从库存里选',
  homePasteLine: '贴一行新线路',
  homePasteHint: 'host:port:user:pass；口令只往上送，任何一次读取都不会再返回',
  homeDefaultNode: '默认节点',
  homeDefaultNodeHint: '可以不填',
  homeNoStock: '库存里没有可以绑的线路',
  homeIdle: '闲置',
  homeStockIdle: (n: number) => `${n} 条闲置`,
  homeStockBusy: (n: number) => `已绑 ${n} 位`,
  homeBindTitle: '绑定家宽',
  homeBindBody: (email: string, line: string) => `${email} 的 Claude 流量改走 ${line}。客户端下次取目录才生效。`,
  homeRebindTitle: '换家宽',
  homeRebindBody: (email: string, line: string) => `${email} 改走 ${line}，没有别人在用的旧线路会被停掉。客户端下次取目录才生效。`,
  homeSharedWarn: (n: number) => `这条线路已经绑了 ${n} 位客户，绑上之后几位客户共用同一条家宽出口。`,
  homeUnbindTitle: '解绑家宽',
  homeUnbindBody: (email: string) => `${email} 的 Claude 流量回到节点的公共出口，线路退回库存。客户端下次取目录才生效。`,
  homeLineRequired: '要贴一行线路，或者从库存里选一条。',

  /* ------------------------------------------------------- Claude 号 */

  claudeSection: 'Claude 号',
  claudeNone: '还没有在用的号',
  claudeFacts: {
    current: '在用账号',
    openedAt: '开通',
    replaceCount: '换过',
    status: '状态',
  } as const,
  claudeReplaceUnit: (n: number) => `${n} 次`,
  claudeStatus: {
    assigned: '在用',
    pooled: '在号池',
    banned: '已封号',
    retired: '已退出',
  } as const,
  claudeOpen: '开通',
  claudeReplace: '换号',
  claudeBan: '封号',
  claudeRef: '账号',
  claudePool: '或从号池里选',
  claudeOpenTitle: '开通 Claude 号',
  claudeOpenBody: (ref: string) => `${ref} 记在这位客户名下，从今天开始算。号池里的这一个也就不能再给别人。`,
  claudeReplaceTitle: '换号',
  claudeReplaceBody: (from: string, to: string) => `${from} 标成已替换，${to} 成为在用的号。换号次数加一。`,
  claudeBanTitle: '封号',
  claudeBanBody: (ref: string) => `${ref} 标成封号，不能再给任何客户用。这位客户会没有在用的号，得再开一个。`,
  claudeBanDetail: '封号情况',
  claudeRefRequired: '要填账号，或者从号池里选一个。',
  claudeEvents: '记录',
  claudeEventWord: {
    opened: '开通',
    replaced: '换号',
    banned: '封号',
    closed: '退出',
    note: '记录',
  } as const,

  /* ---------------------------------------------------------- 设备 */

  deviceActionWord: {
    diagnostic_snapshot: '诊断快照',
    claude_traffic_snapshot: '流量快照',
    refresh_catalog: '刷新目录',
    retry_protection: '重试断线保护',
  } as const,
  deviceActionTitle: (action: string) => `下发${action}`,
  deviceActionBody: (action: string, device: string) => `会给 ${device} 排一次${action}，客户端下次上报时执行，最多等 5 分钟。不会断开正在用的连接。`,
  deviceRetryBody: (device: string) => `只有 ${device} 已经掉进断线保护时才会重试；正连着的不会被断开。`,
  deviceActionStatus: {
    pending: '待下发',
    delivered: '已下发',
    done: '已完成',
    completed: '已完成',
    expired: '已过期',
    failed: '没做成',
  } as const,
  deviceLastAction: (action: string, status: string) => `最近 ${action} · ${status}`,
  deviceNoAction: '还没下发过动作',
  deviceLogsOn: '开 24 小时日志',
  deviceLogsOff: '关掉日志',
  deviceLogsUntil: (when: string) => `日志开到 ${when}`,
  deviceLogsOnTitle: '开 24 小时日志',
  deviceLogsOnBody: (device: string, when: string) => `${device} 会上传原始日志，到 ${when} 自动关。日志里有这台机器的连接细节，只在排障期间开。`,
  deviceLogsOffTitle: '关掉日志',
  deviceLogsOffBody: (device: string) => `${device} 立刻停止上传原始日志。已经传上来的不会删。`,
  deviceRevoke: '吊销',
  deviceRevokeTitle: '吊销设备',
  deviceRevokeBody: (device: string) => `${device} 的登录立刻作废，这台机器会被踢下线，要重新登录才能再用。客户的其他设备不受影响。`,
  deviceRevoked: '已吊销',
  deviceQueued: (action: string) => `已下发${action}`,

  /* ------------------------------------------------- 受保护路由证据 */

  proofSection: '受保护路由证据',
  proofNone: '还没有收到这位客户的 Claude 流量快照',
  proofPending: '最新的一次快照还在等设备回话',
  proofThin: '最新的一次快照没有带回可以核对的结果',
  proofVerdict: {
    confirmed: '看到了独立的家宽路由，出口一致，物理旁路也被挡住了',
    unsafe: '快照里有出口不一致、旁路可达或者受保护流量直连的证据',
    inconclusive: '证据还不够下判断',
  } as const,
  proofFacts: {
    residential: '走家宽的连接',
    proxied: '走通用代理',
    direct: '直连',
    blocked: '被挡下',
    unknown: '看不出',
    observed: '观察到的连接',
    exit: '出口一致性',
    bypass: '物理旁路探针',
    protection: '保护层',
    protectedDirect: '受保护流量直连',
    source: '来源',
    at: '完成时间',
  } as const,
  proofSource: {
    device_action: '设备按需快照',
    periodic_telemetry: '周期遥测',
  } as const,
  proofExit: {
    MATCHED: '一致',
    MISMATCHED: '不一致',
    INCONCLUSIVE: '看不出',
  } as const,
  proofBypass: {
    BLOCKED: '挡住了',
    REACHABLE: '能绕过去',
    INCONCLUSIVE: '看不出',
  } as const,
  proofProtection: {
    whole: '齐全',
    partial: '不齐',
    unreported: '没上报',
  } as const,
  proofResidentialUncounted: '旧版本没有单列',
  proofUnit: (n: number) => `${n} 条`,

  /* ------------------------------------------------------- 诊断报告 */

  reportFacts: {
    code: '编号',
    at: '收到',
    client: '客户端版本',
    os: '系统',
  } as const,
  reportCount: (n: number) => `${n} 份`,

  /* ----------------------------------------------------------- 通用 */

  writeBlocked: '这位客户还没有可以写的账户资料',
  closedNoWrite: '账号已停用，先恢复再改',
  detailUnavailable: '这一块没载入上来',
} as const;
