/** 节点: the fleet dashboard — headline numbers, fleet load, and the node table. */
export const nodesBoardCopy = {
  nodesBoard: {
    lead: '机器健不健康、忙不忙、值不值。负载来自节点探针，连接来自客户端，成本来自账目。',
    stat: {
      fleet: '在役节点',
      problems: '有问题',
      online: '在线客户',
      traffic: '本周期流量',
      rate: '连接成功率 · 7 天',
      cost: '本月节点成本',
    },
    fleetSub: (listed: number, unlisted: number) => `在售 ${listed} · 未上架 ${unlisted}`,
    problemsSub: (lost: number, blocked: number, degraded: number) => `失联 ${lost} · 被墙 ${blocked} · 劣化 ${degraded}`,
    onlineSub: (missing: number) => (missing === 0 ? '每台都有读数' : `${missing} 台没有读数`),
    trafficSub: (quota: string) => `额度合计 ${quota}`,
    trafficNoQuota: '没有登记额度',
    rateSub: (failed: string) => `失败 ${failed} 次`,
    costSub: (pending: number) => (pending === 0 ? '按账目汇总' : `${pending} 台待核对`),
    costSource: '账目',
    load: {
      title: '机器负载',
      lead: '全机队平均与最忙的一台。每一格只算那一刻有上报的机器，所以有机器没上报时，流量合计只是下限。',
      rangeLabel: '负载时间范围',
      range: { '24h': '24 小时', '7d': '7 天' } as const,
      cpu: 'CPU',
      memory: '内存',
      load1: '负载 load1',
      traffic: '流量',
      cpuLead: '占整机的比例',
      memoryLead: '已用占总量',
      load1Lead: '一分钟平均',
      trafficLead: '全机队合计，每秒',
      mean: '平均',
      max: '最忙的一台',
      in: '入',
      out: '出',
      source: '节点探针',
      reporting: (count: number) => `${count} 台在报`,
      empty: '这段时间没有机器报过负载',
      chartLabel: (what: string, range: string) => `过去 ${range}全机队的${what}`,
      rate: (bytes: string) => `${bytes}/s`,
    },
    table: {
      title: '全部节点',
      lead: '问题在前；点一行去节点页',
      filterLabel: '按状态筛选',
      all: '全部',
      search: '搜索节点',
      searchPlaceholder: '名称 / 地区 / 商家',
      source: '节点判定',
      columns: {
        node: '节点',
        status: '状态',
        online: '在线',
        cpu: 'CPU · 24 小时',
        memory: '内存',
        traffic: '本周期流量',
        forward: '客户去程',
        rate: '成功率 · 7 天',
        renew: '到期',
      },
      noMatch: '没有符合条件的节点',
      empty: '一台节点都没有',
      quotaOf: (used: string, pct: string) => `${used} · ${pct}`,
      noQuota: '未设额度',
    },
  },
} as const;
