/** 节点详情: the dashboard half — headline tiles, load, quality and the two paths. */
export const nodeBoardCopy = {
  nodeBoard: {
    stat: {
      online: '在线客户',
      rate: '连接成功率 · 7 天',
      p50: '握手中位 · 7 天',
      traffic: '本周期流量',
      cost: '本月成本',
      expires: '到期',
    },
    onlineOf: (capacity: string) => `容量 ${capacity} 人`,
    onlineNoCapacity: '没有登记容量',
    rateSub: (failed: string) => `失败 ${failed} 次`,
    p50Sub: '客户端报的握手中位',
    trafficOf: (quota: string, share: string) => `额度 ${quota} · 已用 ${share}`,
    trafficNoQuota: '没有登记额度',
    costPerGb: (perGb: string) => `每 GB ${perGb}`,
    costPending: '账目待核对',
    costNone: '账目里没有这台',
    expiresOn: (date: string) => `${date} 到期`,
    expiresNone: '没有登记到期日',
    load: {
      lead: '这台机器自己的忙闲，来自节点探针。',
      rangeLabel: '负载时间范围',
      cpu: 'CPU',
      memory: '内存',
      traffic: '流量',
      connections: '并发连接',
      cpuLead: '占整机的比例',
      memoryLead: '已用占总量',
      trafficLead: (p95: string) => `每秒；95 分位 ${p95}`,
      connectionsLead: (peak: string) => `TCP 连接数；峰值 ${peak}`,
      in: '入',
      out: '出',
      used: '已用',
      open: '连接',
      count: (count: string) => `${count} 条`,
      chartLabel: (what: string, range: string) => `这台机器过去 ${range}的${what}`,
      empty: '这段时间这台机器没有报过负载',
    },
    quality: {
      lead: '客户端连这台机器的结果，按天、按运营商汇总。',
      rateChart: '每日成功率',
      rateChartLead: '按运营商；当天所有尝试里成功的比例',
      rateChartLabel: (range: string) => `这台机器过去 ${range}每天的连接成功率，按运营商`,
      attemptsChart: '每日连接尝试',
      attemptsChartLead: '按运营商叠加',
      attemptsChartLabel: (range: string) => `这台机器过去 ${range}每天的连接尝试次数，按运营商`,
      empty: '这个区间还没有客户连过这台机器',
    },
    paths: {
      forwardLead: '客户端报的，按运营商',
      backLead: '中控机每 5 分钟从大陆三网探一次',
      probes: '最近的探测',
    },
  },
} as const;
