/** 连接质量: the daily success-rate rollup, wherever it is shown. */
export const qualityCopy = {
  quality: {
    title: '连接质量',
    lead: '客户端每次连接的结果，按天汇总；没测到的时段单独计，不算成功也不算失败。',
    source: '每日质量汇总',
    blockTitle: '每日汇总',
    range: { '7d': '7 天', '30d': '30 天' } as const,
    rangeLabel: '时间范围',
    all: '全部',
    stat: {
      rate: '连接成功率',
      attempts: '连接尝试',
      p50: '握手中位',
      outage: '已证实中断',
      coverage: '有效测得',
    },
    failed: (count: string) => `失败 ${count} 次`,
    p50Sub: '各平台、运营商中位数的中位数',
    outageSub: (nodes: number) => (nodes === 0 ? '没有节点中断' : `${nodes} 个节点有中断`),
    unmeasured: (text: string) => `缺测 ${text}`,
    rateChart: '每日成功率',
    rateChartLead: '按平台；当天所有尝试里成功的比例',
    rateChartLabel: (range: string) => `过去 ${range}每天的连接成功率，按平台`,
    attemptsChart: '每日连接尝试',
    attemptsChartLead: '按运营商叠加',
    attemptsChartLabel: (range: string) => `过去 ${range}每天的连接尝试次数，按运营商`,
    outageChart: '每日已证实中断',
    outageChartLead: '全部节点合计，一台机器一天只算一次',
    outageChartLabel: (range: string) => `过去 ${range}每天的已证实中断分钟数`,
    outageStack: '中断',
    nodes: '最差的节点',
    nodesLead: '按成功率从低到高；点一行去节点页',
    nodeColumns: {
      node: '节点',
      rate: '成功率',
      trend: '每日',
      attempts: '尝试',
      p50: '握手中位',
      outage: '中断',
    },
    moreNodes: (count: number) => `另外 ${count} 个节点在节点页`,
    empty: '这个区间还没有连接记录',
    minutes: (n: number) => `${n} 分钟`,
    hours: (n: number) => `${n} 小时`,
  },
} as const;
