/** 家宽: the two residential sections' dashboards — inventory and billed lines. */
export const residentialCopy = {
  residential: {
    inventory: {
      stat: {
        lines: '线路',
        bound: '在用',
        idle: '闲置',
        dead: '失联',
        off: '停用',
        probe: '探测通过率',
      },
      linesSub: (socks: number, catalog: number) => `SOCKS5 ${socks} · 目录 ${catalog}`,
      boundSub: (customers: number) => `带着 ${customers} 位客户`,
      idleSub: '通着，没人用',
      deadSub: (carrying: number) => (carrying === 0 ? '探测全都不通' : `${carrying} 条还绑着客户`),
      offSub: '不会分给客户',
      probeSub: (lines: number) => `${lines} 条线路有探测`,
      table: '线路',
      tableLead: '失联和闲置的排前面；点探测看不出来的，去客户页看他连得怎么样。',
      filterLabel: '按状态筛选',
      all: '全部',
      state: { bound: '在用', idle: '闲置', dead: '失联', off: '停用' } as const,
      source: '中控机探针',
      whoMore: (first: string, rest: number) => `${first} 等 ${rest + 1} 人`,
      noMatch: '这个状态下没有线路',
    },
    lines: {
      stat: {
        lines: '在用线路',
        soon: '30 天内到期',
        rent: '每期租金',
        usage: '本期用量',
        probe: '探测通过率',
        customers: '在用客户',
      },
      linesSub: (retired: number) => (retired === 0 ? '没有退掉的' : `已退 ${retired} 条`),
      soonSub: (deadline: string) => `最近一条 ${deadline}`,
      soonNone: '没有快到期的',
      rentSub: (others: string) => `另有 ${others}`,
      rentOnly: '包月与套餐包合计',
      rentNone: '没有登记价格',
      usageSub: (unmetered: number) => (unmetered === 0 ? '每条都有计量' : `${unmetered} 条没计量`),
      probeSub: (dead: number) => (dead === 0 ? '没有全不通的' : `${dead} 条全不通`),
      customersSub: '按绑定算',
      usageChart: '本期用量',
      usageChartLead: '按线路，上行与下行叠加',
      usageChartLabel: '每条家宽线路本期的上行与下行用量',
      up: '上行',
      down: '下行',
      usageEmpty: '还没有线路报过用量',
      renewals: '快到期',
      renewalsLead: '按到期先后；已过期还在用的排最前',
      renewalsEmpty: '30 天内没有要续的',
      renewalWhen: (deadline: string, date: string) => `${deadline} · ${date}`,
      table: '线路',
      tableLead: '点一行改计费、到期和备注。',
      filterLabel: '按情况筛选',
      filter: { all: '全部', soon: '快到期', unmetered: '没计量', retired: '已退' } as const,
      source: '登记 · 计量 · 探测',
      noMatch: '这个情况下没有线路',
      quotaOf: (used: string, quota: string) => `${used} / ${quota}`,
    },
    action: '操作',
  },
} as const;
