// 今天: incidents, chores, and the two lists behind them.
export const todayCopy = {
  todayVerdict: (incidents: number, customers: number) => `现在 ${incidents} 个事故，影响 ${customers} 位客户`,
  todayClear: (when: string) => `现在没有事故。上次事故 ${when} 已恢复。`,
  todayNeverAny: '现在没有事故。',
  todayTabs: {
    open: '进行中',
    resolved: '最近恢复',
    chores: '待办',
  } as const,
  tabCount: (n: number) => `${n}`,
  severity: {
    severe: '严重',
    warn: '注意',
    notice: '提示',
  } as const,
  incidentImpact: (n: number) => `影响 ${n} 位客户`,
  incidentImpactNode: (n: number) => `影响 ${n} 台节点`,
  incidentOpenFor: '已持续',
  incidentLastSeen: '最后测量',
  incidentResolvedAt: '已恢复',
  incidentPrimary: {
    ack: '认领',
    snooze: '静默 4 小时',
    resolve: '标记已处理',
    note: '备注',
  } as const,
  incidentDrawer: {
    timeline: '时间线',
    affected: '受影响客户',
    evidence: '证据',
    actions: '动作',
    deliveries: '推送记录',
    notePrompt: '写一句备注',
    noteSend: '记下',
  } as const,
  incidentEvent: {
    opened: '开始',
    escalated: '升级',
    deescalated: '降级',
    acked: '已认领',
    snoozed: '已静默',
    note: '备注',
    job: '执行',
    alert: '推送',
    resolved: '已恢复',
  } as const,
  deliveryStatus: {
    pending: '待发',
    sent: '已发',
    failed: '没发出去',
    suppressed: '没重复推送',
  } as const,
  jobStatus: {
    queued: '排队中',
    leased: '执行中',
    succeeded: '成功',
    failed: '失败',
    cancelled: '已取消',
    expired: '已过期',
  } as const,
  emptyIncidents: '没有进行中的事故',
  emptyResolved: '最近 7 天没有恢复记录',
  actionFailed: '动作没做成',
  choreKindOther: '待办',
  choreKind: {
    renew: '续费',
    quota: '额度',
    expiry: '到期',
    version: '版本过旧',
    profile: '缺资料',
  } as const,
  chore: {
    nodeRenew: (node: string, when: string) => `${node} ${when} 续费`,
    nodeQuota: (node: string, pct: string) => `${node} 本期流量已用 ${pct}`,
    nodeProfile: (node: string) => `${node} 还没登记价格与续费日`,
    customerExpiry: (who: string, when: string) => `${who} ${when} 到期`,
    customerQuota: (who: string, pct: string) => `${who} 本期流量已用 ${pct}`,
    customerVersion: (who: string, version: string) => `${who} 还在跑 ${version}`,
    customerProfile: (who: string) => `${who} 没上报过平台与版本`,
  },
  commandCustomers: '客户',
  commandIncidents: '事故',
} as const;
