export const trafficCopy = {
  traffic: {
    lead: '机器区间流量与客户本期用量分开看；累计不冒充速率，缺测不当作零。',
    range: { '24h': '24 小时', '7d': '7 天', '90d': '90 天' },
    rangeLabel: '用量时间范围',
    network: '机器流量总览',
    networkLead: '速率由两次有效累计读数相减，再除以间隔；机器重启、缺测或间隔过长会断线。',
    down: '下行', up: '上行',
    coverage: (down: number, up: number) => `任一时刻最多 ${down} 台提供下行速率、${up} 台提供上行速率；部分机器缺测时合计只是下限。`,
    rate: (bytes: string) => `${bytes}/s`,
    peak: '峰值',
    latest: '最近有效速率',
    top: '机器流量排行',
    topLead: '按每台机器在区间内测得的下行＋上行字节排序，不用机队平均间隔计算。',
    customer: '客户本期累计',
    customerLead: '当前账期的累计与额度，不随上方时间范围变化；点击客户查看明细。',
    quota: (used: string, limit: string) => `${used} / ${limit}`,
    hours: '客户小时用量',
    hoursLead: '沿用小时记账接口的增量与缺口，不补点、不冒充实时速度；无变更小时由接口记为零。',
    empty: '这个窗口没有足够的有效读数，不表示用量为零。',
    customersEmpty: '没有客户用量记录。',
    source: '采集器', usageSource: '小时记账',
    search: '搜索客户',
    back: (window: string) => `返回 ${window} 用量`,
    detailWindow: '对象详情使用各自的时间范围；原用量窗口保留在返回入口。',
  },
} as const;
