import XCTest
@testable import Tono

final class AdmissionTests: XCTestCase {
    func testUnsignedPolicyCannotGrantDirectTraffic() {
        let json = #"{"version":3,"domains":[],"mediaEndpoints":[],"directSuffixes":[{"host":"example.com","ports":[443]}]}"#
        let envelope = PolicyEnvelope(revision: 1, json: json, sha256: PolicyAdmission.digest(Data(json.utf8)), signature: nil)
        XCTAssertThrowsError(try PolicyAdmission.verify(envelope, previousRevision: nil)) {
            XCTAssertEqual($0 as? Blocker, .invalidPolicy)
        }
    }

    func testAuthenticatedCatalogBytesAreNotAnAdmittedConfiguration() throws {
        let json = #"{"revision":7,"yaml":"opaque","sha256":"6d229884c1268bb0ab32d8da315d0fe52f9147228bd830a37bc9fb28a954940d"}"#
        let envelope = try JSONDecoder().decode(CatalogEnvelope.self, from: Data(json.utf8))
        // Expected digest is independently generated by hashlib in static verification.
        XCTAssertThrowsError(try PolicyAdmission.verifyCatalog(envelope)) {
            XCTAssertEqual($0 as? Blocker, .catalogAdapterUnavailable)
        }
    }

    func testMalformedHomeCredentialsDoNotBecomeAbsentRouting() {
        let data = Data(#"{"revision":1,"yaml":"x","sha256":"x","routing":{"homeSocks5":{"host":"example.com","port":1080,"username":"u"}}}"#.utf8)
        XCTAssertThrowsError(try JSONDecoder().decode(CatalogEnvelope.self, from: data))
    }

    func testAuthDecodesCurrentEnvelopeAndIgnoresEnrollmentSecrets() throws {
        let data = Data(#"{"auth":{"accessToken":"fixture-access","refreshToken":"fixture-refresh","user":{"id":"u","email":"example@example.invalid","deviceLimit":3},"device":{"id":"d","name":"phone","current":true},"enrollment":{"authKey":"never-retain-this"}}}"#.utf8)
        let session = try JSONDecoder().decode(AuthEnvelope.self, from: data).auth
        XCTAssertEqual(session.user.deviceLimit, 3)
        XCTAssertEqual(session.device?.current, true)
        XCTAssertFalse(String(decoding: try JSONEncoder().encode(session), as: UTF8.self).contains("never-retain-this"))
    }
}
