-- Security and D1 quota hardening discovered by the adversarial audit.
PRAGMA foreign_keys = ON;

-- D1 batch() is a SQLite transaction, but application-side reads between
-- statements are not. A rotation records the victims selected inside the same
-- write transaction that revokes them and occupies the new device slot.
CREATE TABLE device_rotation_victims (
  rotation_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  PRIMARY KEY (rotation_id, device_id)
);

-- A zero-row target UPDATE would otherwise commit the victim revocations. The
-- final guard INSERT converts that stale-target outcome into a constraint error,
-- making D1 roll the whole batch back before the caller retries.
CREATE TABLE device_rotation_guards (
  rotation_id TEXT PRIMARY KEY,
  valid INTEGER NOT NULL CHECK(valid = 1)
);

-- Session creation happens after ensureDevice() returns. Without a database
-- boundary, a concurrent rotation can revoke that device first and the losing
-- login can then insert an unrevoked session. The session is initially blocked
-- by auth()'s device check, but would become usable again if the same
-- installation were later re-enrolled. SQLite serializes this trigger with the
-- rotation transaction: either the session exists in time to be revoked by the
-- rotation, or its insert is rejected after the device/account becomes
-- ineligible.
UPDATE sessions
SET revoked_at = unixepoch()
WHERE revoked_at IS NULL
  AND device_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM devices
    JOIN users ON users.id = devices.user_id
    WHERE devices.id = sessions.device_id
      AND devices.user_id = sessions.user_id
      AND (
        devices.status = 'active'
        OR (
          devices.status = 'pending'
          AND devices.pending_expires_at IS NOT NULL
          AND devices.pending_expires_at > unixepoch()
        )
      )
      AND users.status = 'active'
      AND (users.expires_at IS NULL OR users.expires_at > unixepoch())
      AND (users.quota_bytes IS NULL OR users.usage_bytes < users.quota_bytes)
  );

CREATE TRIGGER sessions_require_eligible_device
BEFORE INSERT ON sessions
WHEN NEW.device_id IS NOT NULL AND NOT EXISTS (
  SELECT 1
  FROM devices
  JOIN users ON users.id = devices.user_id
  WHERE devices.id = NEW.device_id
    AND devices.user_id = NEW.user_id
    AND (
      devices.status = 'active'
      OR (
        devices.status = 'pending'
        AND devices.pending_expires_at IS NOT NULL
        AND devices.pending_expires_at > unixepoch()
      )
    )
    AND users.status = 'active'
    AND (users.expires_at IS NULL OR users.expires_at > unixepoch())
    AND (users.quota_bytes IS NULL OR users.usage_bytes < users.quota_bytes)
)
BEGIN
  SELECT RAISE(ABORT, 'SESSION_DEVICE_INELIGIBLE');
END;

-- Shared legacy credentials stay accepted until an operator has provisioned
-- per-node authentication, every active device has a credential, every active
-- exit has acknowledged that roster, and the placeholder catalog is live.
CREATE TABLE exit_credential_rollout (
  singleton_id INTEGER PRIMARY KEY CHECK(singleton_id = 1),
  phase TEXT NOT NULL DEFAULT 'dual'
    CHECK(phase IN ('dual', 'device_only')),
  updated_at INTEGER NOT NULL
);
INSERT INTO exit_credential_rollout(singleton_id, phase, updated_at)
VALUES(1, 'dual', unixepoch());

-- Tokens are generated by the control plane and returned once. Only a hash is
-- retained, which permits per-node rotation/revocation and binds usage reports
-- to the authenticated node instead of trusting a caller-supplied source id.
CREATE TABLE exit_nodes (
  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 64),
  name TEXT NOT NULL UNIQUE CHECK(length(name) BETWEEN 1 AND 100),
  token_hash TEXT NOT NULL UNIQUE CHECK(length(token_hash) = 43),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK(status IN ('active', 'disabled')),
  last_roster_at INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX exit_nodes_status_roster
  ON exit_nodes(status, last_roster_at);

-- Application preflight makes operator errors readable, while this trigger is
-- the final atomic boundary. Without it an active device or exit node created
-- between the preflight reads and the phase UPDATE could retire the shared
-- credential before every active node had installed the replacement roster.
CREATE TRIGGER exit_credential_rollout_ready
BEFORE UPDATE OF phase ON exit_credential_rollout
WHEN NEW.phase = 'device_only' AND OLD.phase = 'dual' AND (
  NOT EXISTS (
    SELECT 1 FROM exit_nodes WHERE status = 'active'
  )
  OR EXISTS (
    SELECT 1
    FROM devices
    LEFT JOIN device_exit_credentials credentials
      ON credentials.device_id = devices.id
    WHERE devices.status IN ('pending', 'active')
      AND credentials.device_id IS NULL
  )
  OR EXISTS (
    SELECT 1
    FROM exit_nodes
    WHERE status = 'active'
      AND last_roster_at <= COALESCE((
        SELECT MAX(credentials.created_at)
        FROM device_exit_credentials credentials
        JOIN devices ON devices.id = credentials.device_id
        WHERE devices.status IN ('pending', 'active')
      ), 0)
  )
)
BEGIN
  SELECT RAISE(ABORT, 'EXIT_CREDENTIAL_ROLLOUT_NOT_READY');
END;

-- Replace the old OR retention scan with two indexable bounded deletes.
DROP INDEX IF EXISTS sessions_retention;
CREATE INDEX sessions_revoked_retention
  ON sessions(revoked_at) WHERE revoked_at IS NOT NULL;
CREATE INDEX sessions_expiry_retention
  ON sessions(expires_at) WHERE revoked_at IS NULL;

-- Legacy-v1 report ids are only retry/idempotency evidence. The cumulative
-- billing authority lives in usage_report_sources, so old evidence can be
-- pruned. Protocol v2 does not insert report-id rows at all: its authenticated
-- source and strictly increasing observed_at watermark provide durable replay
-- protection without paying for an insert and later indexed delete per poll.
-- Protocol v2 replaces each agent's local wall clock with a server-roster
-- monotonic watermark. v1 remains accepted until that source's first v2 report,
-- allowing an already queued clock-skewed cumulative value to settle during the
-- upgrade; after cutover, v1 can never move that source again.
ALTER TABLE usage_reports ADD COLUMN protocol_version INTEGER NOT NULL DEFAULT 1
  CHECK(protocol_version IN (1, 2));
ALTER TABLE usage_report_sources ADD COLUMN protocol_version INTEGER NOT NULL DEFAULT 1
  CHECK(protocol_version IN (1, 2));

DROP TRIGGER usage_reports_immutable_insert;
CREATE TRIGGER usage_reports_immutable_insert
BEFORE INSERT ON usage_reports
WHEN EXISTS (
  SELECT 1
  FROM usage_reports
  WHERE report_id = NEW.report_id
    AND (
      user_id != NEW.user_id
      OR source_id != NEW.source_id
      OR protocol_version != NEW.protocol_version
      OR total_bytes != NEW.total_bytes
      OR observed_at != NEW.observed_at
    )
)
BEGIN
  SELECT RAISE(ABORT, 'USAGE_REPORT_CONFLICT');
END;

CREATE INDEX usage_reports_created_at ON usage_reports(created_at);

-- A catalog request used to scan every home exit only to build the restricted
-- proxy-name set. Keep that derived set in one row and maintain it at the table
-- boundary so every write path (including operator SQL) stays coherent.
CREATE TABLE home_exit_catalog_names (
  singleton_id INTEGER PRIMARY KEY CHECK(singleton_id = 1),
  proxy_names_json TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
INSERT INTO home_exit_catalog_names(singleton_id, proxy_names_json, updated_at)
SELECT 1,
       COALESCE(json_group_array(proxy_name), '[]'),
       unixepoch()
FROM home_exits
WHERE status = 'active' AND kind = 'catalog';

CREATE TRIGGER home_exit_catalog_names_insert
AFTER INSERT ON home_exits
BEGIN
  UPDATE home_exit_catalog_names
     SET proxy_names_json = COALESCE((
           SELECT json_group_array(proxy_name)
           FROM home_exits
           WHERE status = 'active' AND kind = 'catalog'
         ), '[]'),
         updated_at = unixepoch()
   WHERE singleton_id = 1;
END;

CREATE TRIGGER home_exit_catalog_names_update
AFTER UPDATE OF proxy_name, status, kind ON home_exits
BEGIN
  UPDATE home_exit_catalog_names
     SET proxy_names_json = COALESCE((
           SELECT json_group_array(proxy_name)
           FROM home_exits
           WHERE status = 'active' AND kind = 'catalog'
         ), '[]'),
         updated_at = unixepoch()
   WHERE singleton_id = 1;
END;

CREATE TRIGGER home_exit_catalog_names_delete
AFTER DELETE ON home_exits
BEGIN
  UPDATE home_exit_catalog_names
     SET proxy_names_json = COALESCE((
           SELECT json_group_array(proxy_name)
           FROM home_exits
           WHERE status = 'active' AND kind = 'catalog'
         ), '[]'),
         updated_at = unixepoch()
   WHERE singleton_id = 1;
END;
